### PR TITLE
Add Simplified Chinese

### PR DESCRIPTION
**Pull request by 9N9N7S**

### CODE REVIEW

**Comment by DABOI69420** [comment]
ayo wtf r u

**Comment by DABOI69420** [comment]
Sure we will add it

**Comment by 9N9N7S** [comment]
Thanks

**Comment by Bonkersboy2017** [comment]
Do you have translations for these?

  "item.dinocraft.dino_egg": "Dino Egg",
  "item.dinocraft.indoraptor_egg": "Indo Egg",
  "item.dinocraft.indoraptor_embryo": "Indo Embryo",
  "item.dinocraft.dna_strand": "DNA Strand",
  "item.dinocraft.amber_gem": "Amber Gem ",
  "item.dinocraft.amber_pickaxe": "Amber Pickaxe",
  "item.dinocraft.amber_axe": "Amber Axe",
  "item.dinocraft.amber_hoe": "Amber Hoe",
  "item.dinocraft.amber_sword": "Amber Sword",
  "item.dinocraft.amber_shovel": "Amber Shovel",
  "block.dinocraft.amber_block":"Amber Block",
  "block.dinocraft.amber_bricks":"Amber Bricks",
  "block.dinocraft.amber_ore":"Amber Ore"


Amber Helmet ->
Amber Chestplate -> 
Amber Leggings ->
Amber Boots ->

**Comment by 9N9N7S** [comment]
"item.dinocraft.dino_egg":"恐龙蛋",
"item.dinocraft.indoraptor_egg":"原始人蛋",
"item.dinocraft.indoraptor_embryo":"原始人胚胎",
"item.dinocraft.dna_strand":"DNA序列",
"item.dinocraft.amber_gem":"琥珀宝石 ",
"item.dinocraft.amber_pickaxe":"琥珀镐",
"item.dinocraft.amber_axe":"琥珀斧头",
"item.dinocraft.amber_hoe":"琥珀锄头",
"item.dinocraft.amber_sword":"琥珀剑",
"item.dinocraft.amber_shovel":"琥珀铲子",
"block.dinocraft.amber_block":"琥珀块",
"block.dinocraft.amber_bricks":"琥珀砖",
"block.dinocraft.amber_ore":"琥珀矿石"

琥珀色头盔 ->
琥珀胸甲 ->
琥珀色紧身裤 ->
琥珀色靴子 ->

**Pull request closed without merging**
